name: Release Drafter

on:
  push:
    branches:
      - master # 在 master 分支发生更新时执行此 action

jobs:
  draft_release:
    name: Draft release
    runs-on: ubuntu-latest
    steps:
      - name: Publish Release Draft
        id: publish_release
        uses: toolmantim/release-drafter@v5.2.0
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        id: package
        run: mvn -B package --file pom.xml -Dmaven.test.skip=true
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.publish_release.outputs.upload_url }}
          asset_path: target/fizz-gateway-community-${{ steps.package.outputs.version }}.jar
          asset_name: fizz-gateway-community-${{ steps.package.outputs.version }}.jar
          asset_content_type: application/java-archive
